package com.example.thindie.wantmoex.data

import com.example.thindie.wantmoex.data.mappers.map
import com.example.thindie.wantmoex.data.network.dto.CoinDTO
import com.example.thindie.wantmoex.data.network.dto.multifull.CoinRawMultiFullResponseDTO
import com.example.thindie.wantmoex.data.network.dto.toCoinDTO
import com.example.thindie.wantmoex.data.network.dto.toCoinListDTO
import com.example.thindie.wantmoex.data.network.dto.totalvolfull.CoinRawTotalVolFullResponseDTO
import com.example.thindie.wantmoex.data.network.retrofit.CryptoCoinsApiService
import com.example.thindie.wantmoex.data.storage.CoinDBModel
import com.example.thindie.wantmoex.data.storage.CoinDao
import com.example.thindie.wantmoex.data.storage.favourites.FavouriteCoinDBModel
import com.example.thindie.wantmoex.data.storage.favourites.FavouriteCoinDao
import com.example.thindie.wantmoex.di.DispatchersModule
import com.example.thindie.wantmoex.domain.CryptoCoinRepository
import com.example.thindie.wantmoex.domain.FavouriteCoinsRepository
import com.example.thindie.wantmoex.domain.entities.Coin
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CryptoCoinsRepositoryImpl @Inject constructor(
    private val cryptoCoinsApiService: CryptoCoinsApiService,
    private val appDataBase: CoinDao,
    private val favouriteCoinsDataBase: FavouriteCoinDao,
    @DispatchersModule.IODispatcher private val IODispatcher: CoroutineDispatcher
) : CryptoCoinRepository, FavouriteCoinsRepository {


    override suspend fun getAllCoins(): Flow<List<Coin>?> {

        val nullableDTOList = rawFullCoinsDTO().toCoinListDTO()

        if (fromDBCoins().isEmpty()) {
            return if (!nullableDTOList.isNullOrEmpty()) {
                nullableDTOList._DBInsert()
                flow { emit(fromDBCoins()) }
            } else flow { emit(null) }
        }
        return flow {
            emit(fromDBCoins())
        }
    }

    override suspend fun getCoin(fromSymbol: String): Coin? {

        val coinDTO =
            getRawCoinData(fromSymbol).toCoinDTO() ?: return fromDBCoins().containsCoin(fromSymbol)
        return coinDTO.map().map()
    }

    override suspend fun getAllFavoriteCoins(): Flow<List<String>> {
        val coinsIdList = getFavoriteCoinsList().map {
            it.fromSymbol
        }
        return flow { emit(coinsIdList) }
    }

    override suspend fun deleteFromFavoriteCoins(deleteCoins: List<String>) {
        getFavoriteCoinsList().forEach {
            if (deleteCoins.contains(it.fromSymbol)) {
                withContext(IODispatcher) {
                    favouriteCoinsDataBase.deleteFavouriteCoin(it.id)
                }
            }
        }
    }

    override suspend fun addToFavoriteCoins(addCoins: List<String>) {
        addCoins.forEach {
            favouriteCoinsDataBase
                .insertFavouriteCoin(FavouriteCoinDBModel(fromSymbol = it, id = AUTOGENERATED))
        }
    }

    private suspend fun fromDBCoins() = run { _DBcoins().map { it.map() } }
    private suspend fun getFavoriteCoinsList() =
        run { favouriteCoinsDataBase.getAllFavouriteCoins() }

    private suspend fun getRawCoinData(fromSymbol: String): CoinRawMultiFullResponseDTO {
        return cryptoCoinsApiService.getCoin(fSyms = fromSymbol)
    }

    private suspend fun _DBcoins(): List<CoinDBModel> {
        return appDataBase.getAllCoins()
    }

    private suspend fun List<CoinDTO>?._DBInsert() {
        this?.map { it.map() }?.let { appDataBase.insertPriceList(it) }
    }

    private fun List<Coin>.containsCoin(fromSymbol: String): Coin? {
        var coin: Coin? = null
        this.forEach {
            if (it.fromSymbol == fromSymbol) {
                coin = it
            }
        }
        return coin
    }

    private suspend fun rawFullCoinsDTO(): CoinRawTotalVolFullResponseDTO? {
        return try {
            cryptoCoinsApiService.getTopCoins(limit = LIMIT)
        } catch (_: Exception) {
            null
        }
    }

    companion object {
        private const val LIMIT = 30
        private const val AUTOGENERATED = 0
    }
}