package com.example.thindie.wantmoex.data

import com.example.thindie.wantmoex.data.mappers.map
import com.example.thindie.wantmoex.data.network.dto.CoinDTO
import com.example.thindie.wantmoex.data.network.dto.fromMultiFullToDTO
import com.example.thindie.wantmoex.data.network.dto.fromTotalVolFullToDTOList
import com.example.thindie.wantmoex.data.network.dto.multifull.CoinRawMultiFullResponseDTO
import com.example.thindie.wantmoex.data.network.dto.totalvolfull.CoinRawTotalVolFullResponseDTO
import com.example.thindie.wantmoex.data.network.retrofit.CryptoCoinsApiService
import com.example.thindie.wantmoex.data.storage.AppDataBase
import com.example.thindie.wantmoex.data.storage.CoinDBModel
import com.example.thindie.wantmoex.data.storage.favourites.FavouriteCoinDBModel
import com.example.thindie.wantmoex.data.storage.favourites.FavouriteCoinsDataBase
import com.example.thindie.wantmoex.di.DispatchersModule
import com.example.thindie.wantmoex.domain.CryptoCoinRepository
import com.example.thindie.wantmoex.domain.FavouriteCoinsRepository
import com.example.thindie.wantmoex.domain.entities.Coin
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CryptoCoinsRepositoryImpl @Inject constructor(
    private val cryptoCoinsApiService: CryptoCoinsApiService,
    private val appDataBase: AppDataBase,
    private val favouriteCoinsDataBase: FavouriteCoinsDataBase,
    @DispatchersModule.IODispatcher private val IODispatcher: CoroutineDispatcher
) : CryptoCoinRepository, FavouriteCoinsRepository {


    override suspend fun getAllCoins(): Flow<List<Coin>?> {

        suspend fun fromDBCoins()  = run { _DBcoins().map { it.map() } }
        val nullableDTOList = rawFullCoinsDTO().toCoinListDTO()

        if (fromDBCoins().isEmpty()) {
            return if (!nullableDTOList.isNullOrEmpty()) {
                nullableDTOList._DBInsert()
                flow { emit( fromDBCoins() )  }
            } else flow { emit(null) }
        }
        return flow {
            emit(fromDBCoins())
        }
    }

    override suspend fun getCoin(fromSymbol: String): Coin? {

        suspend fun fromDBCoins()  = run { _DBcoins().map { it.map() } }
         val coinDTO  = getRawCoinData(fromSymbol).toCoinDTO() ?: return  fromDBCoins().containsCoin(fromSymbol)
        return coinDTO.map().map()
    }

    override suspend fun getAllFavoriteCoins(): Flow<List<String>> {
        val coinsIdList = favouriteCoinsDataBase.coinFavouriteListDao().getAllFavouriteCoins().map {
            it.fromSymbol
        }
        return flow { emit(coinsIdList) }
     }

    override suspend fun deleteFromFavoriteCoins(deleteCoins: List<String>) {
        val listOfID = favouriteCoinsDataBase.coinFavouriteListDao().getAllFavouriteCoins()
        listOfID.forEach {
            if (deleteCoins.contains(it.fromSymbol)) {
                withContext(IODispatcher) {
                    favouriteCoinsDataBase.coinFavouriteListDao().deleteFavouriteCoin(it.id)
                }
             }
        }
     }

    override suspend fun addToFavoriteCoins(addCoins: List<String>) {
        addCoins.forEach {
            favouriteCoinsDataBase.coinFavouriteListDao()
                .insertFavouriteCoin(FavouriteCoinDBModel(fromSymbol = it, id = AUTOGENERATED))
        }
    }

    private fun CoinRawTotalVolFullResponseDTO?.toCoinListDTO() : List<CoinDTO>?{
       return  this?.let { fromTotalVolFullToDTOList(it) }
    }

    private fun CoinRawMultiFullResponseDTO?.toCoinDTO() : CoinDTO?{
      return this?.let { fromMultiFullToDTO(it) }?.get(0)
    }

    private suspend fun getRawCoinData(fromSymbol: String) : CoinRawMultiFullResponseDTO {
       return cryptoCoinsApiService.getCoin(fSyms = fromSymbol)
    }
    private suspend fun _DBcoins() : List<CoinDBModel>{
      return  appDataBase.coinListDao().getAllCoins()
    }

    private suspend fun List<CoinDTO>?._DBInsert(){
        this?.map {  it.map() }?.let { appDataBase.coinListDao().insertPriceList(it) }
    }

    private fun List<Coin>.containsCoin(fromSymbol: String) : Coin?{
        var coin: Coin? = null
        this.forEach {
            if(it.fromSymbol == fromSymbol){ coin = it  }
        }
        return coin
    }

    private suspend fun rawFullCoinsDTO() : CoinRawTotalVolFullResponseDTO?{
      return  try {
            cryptoCoinsApiService.getTopCoins(limit = LIMIT)
        } catch (_: Exception) {
            null
        }
    }

    companion object {
        private const val LIMIT = 30
        private const val AUTOGENERATED = 0
        private const val INDEX = 0
        private const val SERIOUS_EXCEPTION = "it cannot happen obviously"
    }
}